// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	client "github.com/coinbase/coinbase-sdk-go/gen/client"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// StakeAPI is an autogenerated mock type for the StakeAPI type
type StakeAPI struct {
	mock.Mock
}

// BuildStakingOperation provides a mock function with given fields: ctx
func (_m *StakeAPI) BuildStakingOperation(ctx context.Context) client.ApiBuildStakingOperationRequest {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for BuildStakingOperation")
	}

	var r0 client.ApiBuildStakingOperationRequest
	if rf, ok := ret.Get(0).(func(context.Context) client.ApiBuildStakingOperationRequest); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.ApiBuildStakingOperationRequest)
	}

	return r0
}

// BuildStakingOperationExecute provides a mock function with given fields: r
func (_m *StakeAPI) BuildStakingOperationExecute(r client.ApiBuildStakingOperationRequest) (*client.StakingOperation, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for BuildStakingOperationExecute")
	}

	var r0 *client.StakingOperation
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiBuildStakingOperationRequest) (*client.StakingOperation, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiBuildStakingOperationRequest) *client.StakingOperation); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.StakingOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiBuildStakingOperationRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiBuildStakingOperationRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FetchHistoricalStakingBalances provides a mock function with given fields: ctx, networkId, addressId
func (_m *StakeAPI) FetchHistoricalStakingBalances(ctx context.Context, networkId string, addressId string) client.ApiFetchHistoricalStakingBalancesRequest {
	ret := _m.Called(ctx, networkId, addressId)

	if len(ret) == 0 {
		panic("no return value specified for FetchHistoricalStakingBalances")
	}

	var r0 client.ApiFetchHistoricalStakingBalancesRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) client.ApiFetchHistoricalStakingBalancesRequest); ok {
		r0 = rf(ctx, networkId, addressId)
	} else {
		r0 = ret.Get(0).(client.ApiFetchHistoricalStakingBalancesRequest)
	}

	return r0
}

// FetchHistoricalStakingBalancesExecute provides a mock function with given fields: r
func (_m *StakeAPI) FetchHistoricalStakingBalancesExecute(r client.ApiFetchHistoricalStakingBalancesRequest) (*client.FetchHistoricalStakingBalances200Response, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for FetchHistoricalStakingBalancesExecute")
	}

	var r0 *client.FetchHistoricalStakingBalances200Response
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiFetchHistoricalStakingBalancesRequest) (*client.FetchHistoricalStakingBalances200Response, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiFetchHistoricalStakingBalancesRequest) *client.FetchHistoricalStakingBalances200Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.FetchHistoricalStakingBalances200Response)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiFetchHistoricalStakingBalancesRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiFetchHistoricalStakingBalancesRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// FetchStakingRewards provides a mock function with given fields: ctx
func (_m *StakeAPI) FetchStakingRewards(ctx context.Context) client.ApiFetchStakingRewardsRequest {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for FetchStakingRewards")
	}

	var r0 client.ApiFetchStakingRewardsRequest
	if rf, ok := ret.Get(0).(func(context.Context) client.ApiFetchStakingRewardsRequest); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.ApiFetchStakingRewardsRequest)
	}

	return r0
}

// FetchStakingRewardsExecute provides a mock function with given fields: r
func (_m *StakeAPI) FetchStakingRewardsExecute(r client.ApiFetchStakingRewardsRequest) (*client.FetchStakingRewards200Response, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for FetchStakingRewardsExecute")
	}

	var r0 *client.FetchStakingRewards200Response
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiFetchStakingRewardsRequest) (*client.FetchStakingRewards200Response, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiFetchStakingRewardsRequest) *client.FetchStakingRewards200Response); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.FetchStakingRewards200Response)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiFetchStakingRewardsRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiFetchStakingRewardsRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetExternalStakingOperation provides a mock function with given fields: ctx, networkId, addressId, stakingOperationId
func (_m *StakeAPI) GetExternalStakingOperation(ctx context.Context, networkId string, addressId string, stakingOperationId string) client.ApiGetExternalStakingOperationRequest {
	ret := _m.Called(ctx, networkId, addressId, stakingOperationId)

	if len(ret) == 0 {
		panic("no return value specified for GetExternalStakingOperation")
	}

	var r0 client.ApiGetExternalStakingOperationRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) client.ApiGetExternalStakingOperationRequest); ok {
		r0 = rf(ctx, networkId, addressId, stakingOperationId)
	} else {
		r0 = ret.Get(0).(client.ApiGetExternalStakingOperationRequest)
	}

	return r0
}

// GetExternalStakingOperationExecute provides a mock function with given fields: r
func (_m *StakeAPI) GetExternalStakingOperationExecute(r client.ApiGetExternalStakingOperationRequest) (*client.StakingOperation, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetExternalStakingOperationExecute")
	}

	var r0 *client.StakingOperation
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiGetExternalStakingOperationRequest) (*client.StakingOperation, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiGetExternalStakingOperationRequest) *client.StakingOperation); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.StakingOperation)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiGetExternalStakingOperationRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiGetExternalStakingOperationRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetStakingContext provides a mock function with given fields: ctx
func (_m *StakeAPI) GetStakingContext(ctx context.Context) client.ApiGetStakingContextRequest {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStakingContext")
	}

	var r0 client.ApiGetStakingContextRequest
	if rf, ok := ret.Get(0).(func(context.Context) client.ApiGetStakingContextRequest); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(client.ApiGetStakingContextRequest)
	}

	return r0
}

// GetStakingContextExecute provides a mock function with given fields: r
func (_m *StakeAPI) GetStakingContextExecute(r client.ApiGetStakingContextRequest) (*client.StakingContext, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetStakingContextExecute")
	}

	var r0 *client.StakingContext
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiGetStakingContextRequest) (*client.StakingContext, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiGetStakingContextRequest) *client.StakingContext); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.StakingContext)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiGetStakingContextRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiGetStakingContextRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetValidator provides a mock function with given fields: ctx, networkId, assetId, validatorId
func (_m *StakeAPI) GetValidator(ctx context.Context, networkId string, assetId string, validatorId string) client.ApiGetValidatorRequest {
	ret := _m.Called(ctx, networkId, assetId, validatorId)

	if len(ret) == 0 {
		panic("no return value specified for GetValidator")
	}

	var r0 client.ApiGetValidatorRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) client.ApiGetValidatorRequest); ok {
		r0 = rf(ctx, networkId, assetId, validatorId)
	} else {
		r0 = ret.Get(0).(client.ApiGetValidatorRequest)
	}

	return r0
}

// GetValidatorExecute provides a mock function with given fields: r
func (_m *StakeAPI) GetValidatorExecute(r client.ApiGetValidatorRequest) (*client.Validator, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for GetValidatorExecute")
	}

	var r0 *client.Validator
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiGetValidatorRequest) (*client.Validator, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiGetValidatorRequest) *client.Validator); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.Validator)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiGetValidatorRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiGetValidatorRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// ListValidators provides a mock function with given fields: ctx, networkId, assetId
func (_m *StakeAPI) ListValidators(ctx context.Context, networkId string, assetId string) client.ApiListValidatorsRequest {
	ret := _m.Called(ctx, networkId, assetId)

	if len(ret) == 0 {
		panic("no return value specified for ListValidators")
	}

	var r0 client.ApiListValidatorsRequest
	if rf, ok := ret.Get(0).(func(context.Context, string, string) client.ApiListValidatorsRequest); ok {
		r0 = rf(ctx, networkId, assetId)
	} else {
		r0 = ret.Get(0).(client.ApiListValidatorsRequest)
	}

	return r0
}

// ListValidatorsExecute provides a mock function with given fields: r
func (_m *StakeAPI) ListValidatorsExecute(r client.ApiListValidatorsRequest) (*client.ValidatorList, *http.Response, error) {
	ret := _m.Called(r)

	if len(ret) == 0 {
		panic("no return value specified for ListValidatorsExecute")
	}

	var r0 *client.ValidatorList
	var r1 *http.Response
	var r2 error
	if rf, ok := ret.Get(0).(func(client.ApiListValidatorsRequest) (*client.ValidatorList, *http.Response, error)); ok {
		return rf(r)
	}
	if rf, ok := ret.Get(0).(func(client.ApiListValidatorsRequest) *client.ValidatorList); ok {
		r0 = rf(r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*client.ValidatorList)
		}
	}

	if rf, ok := ret.Get(1).(func(client.ApiListValidatorsRequest) *http.Response); ok {
		r1 = rf(r)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*http.Response)
		}
	}

	if rf, ok := ret.Get(2).(func(client.ApiListValidatorsRequest) error); ok {
		r2 = rf(r)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewStakeAPI creates a new instance of StakeAPI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStakeAPI(t interface {
	mock.TestingT
	Cleanup(func())
}) *StakeAPI {
	mock := &StakeAPI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
